# Generated by Django 4.1.3 on 2022-11-17 09:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLetter',
            fields=[
                ('inv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_companyname', models.CharField(max_length=150)),
                ('from_address', models.CharField(max_length=150)),
                ('from_phonenumber', models.CharField(max_length=150)),
                ('from_emailaddress', models.CharField(max_length=150)),
                ('to_consigneeename', models.CharField(max_length=150)),
                ('to_phonenumber', models.CharField(max_length=150)),
                ('to_address', models.CharField(max_length=150)),
                ('from_personname', models.CharField(max_length=150)),
                ('from_countries', models.CharField(max_length=150)),
                ('from_town', models.CharField(max_length=150)),
                ('to_countries', models.CharField(max_length=150)),
                ('to_town', models.CharField(max_length=150)),
                ('package_kind', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('weight', models.CharField(max_length=15)),
                ('length', models.CharField(max_length=150)),
                ('width', models.CharField(max_length=150)),
                ('height', models.CharField(max_length=150)),
                ('airfreight_charges', models.CharField(max_length=150)),
                ('other_charges', models.CharField(max_length=150)),
                ('insur_amount', models.CharField(max_length=150)),
                ('nvd', models.CharField(max_length=150)),
                ('ncv', models.CharField(max_length=150)),
                ('handling_info', models.CharField(max_length=150)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_letter',
            },
        ),
    ]
