# Generated by Django 4.1.3 on 2022-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_invoiceletter_from_sendertown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceletter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceletter',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
