# Generated by Django 4.1.3 on 2023-01-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_invoiceletter_inv_fk_invoiceletter_inv_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceletter',
            name='user_saved_by',
        ),
        migrations.DeleteModel(
            name='airwaybill',
        ),
        migrations.DeleteModel(
            name='InvoiceLetter',
        ),
    ]
