# Generated by Django 4.1.3 on 2022-11-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_invoiceletter_user_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceletter',
            name='user_saved_by',
        ),
    ]
