# Generated by Django 4.1.3 on 2022-11-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_remove_invoiceletter_user_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceletter',
            name='user_saved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='inventryuser'),
            preserve_default=False,
        ),
    ]
