# Generated by Django 4.1.3 on 2023-01-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airwaybill',
        ),
    ]
