# Generated by Django 4.1.3 on 2022-11-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_airwaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='airwaybill',
            name='inv_id',
            field=models.ForeignKey(default='a7598f92-31fd-4f9c-9525-8c0b6283974c', on_delete=django.db.models.deletion.CASCADE, to='services.invoiceletter', verbose_name='inv_awb_fk'),
            preserve_default=False,
        ),
    ]
