# Generated by Django 4.1.3 on 2023-01-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_invoiceletter_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceletter',
            name='user_saved_by',
        ),
    ]
