# Generated by Django 4.1.3 on 2023-01-03 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_airwaybill_airport_of_dest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="flight_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
