# Generated by Django 4.1.3 on 2023-01-03 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_remove_airwaybill_flight_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="airwaybill",
            name="flight_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
