# Generated by Django 4.1.3 on 2023-01-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_airwaybill_airport_of_dest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="airfreight_charges",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="handling_info",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="insur_amount",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="ncv",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="nvd",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="other_charges",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
