# Generated by Django 4.1.3 on 2023-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_alter_airwaybill_airfreight_charges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="Rate_charge",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_airfreight_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_charges_dest",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_other_charges_agent",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_other_charges_carrier",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_tax",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_total_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="c_valuation_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="cheargeable_weight",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="other_charges_2",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_airfreight_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_charges_dest",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_currency_conversion",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_other_charges_agent",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_other_charges_carrier",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_tax",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_total_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="p_valuation_charges",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="airwaybill",
            name="total_charge",
            field=models.FloatField(default=0),
        ),
    ]
