# Generated by Django 4.1.3 on 2023-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0018_alter_airwaybill_airport_of_departure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="AIRPORT_OF_DEST",
            field=models.CharField(default=False, max_length=150, null=True),
        ),
    ]
