# Generated by Django 4.1.3 on 2023-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0019_alter_airwaybill_airport_of_dest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="Airport_of_destination",
            field=models.CharField(default=False, max_length=150, null=True),
        ),
    ]
