# Generated by Django 4.1.3 on 2023-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_alter_airwaybill_carrier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="Requested_routing",
            field=models.CharField(default=False, max_length=150, null=True),
        ),
    ]
