# Generated by Django 4.1.3 on 2023-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_alter_airwaybill_c_airfreight_charges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airwaybill",
            name="other_charges_2",
            field=models.FloatField(default=0, null=True),
        ),
    ]
